name: items_selector
description: "A Flutter package for selecting single or multiple items from a list or grid"
version: 0.0.1
homepage: "https://github.com/SinaSys/items_selector"

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  assets:
    - assets/images/widgets/single_list_item/
    - assets/images/widgets/multi_list_item/
    - assets/images/widgets/single_grid_item/
    - assets/images/widgets/multi_grid_item/
    - assets/images/options/single/
    - assets/images/options/multi/

